const SEASON_CODE = 'SEASON_CD'
const SEASON_YEAR = 'SEASON_YR'
const STYLE_NUMBER = 'STYLE_NBR'
const STYLE_CODE = 'STYLE_CW_CD'
const MATERIAL_NUMBER = 'ITEM_NBR'
const GCW_COLOR = 'GCW#'
const COMPONENT_ORD = 'COMPONENT_ORD'
const GCW_ORD = 'GCW_ORD'
const ITEM_COLOR_CODE = 'ITEM_COLOR_CD'
const STATUS = 'STATUS'
const VENDOR_CODE = 'VEND_CD'
const QTY = 'QTY'
const MSC_CODE = 'MSC_CODE'
const CATEGORY = 'ITEM_TYPE_1'

module.exports = {
    SEASON_CODE,
    SEASON_YEAR,
    STYLE_NUMBER,
    STYLE_CODE,
    MATERIAL_NUMBER,
    GCW_COLOR,
    COMPONENT_ORD,
    GCW_ORD,
    ITEM_COLOR_CODE,
    STATUS,
    VENDOR_CODE,
    QTY,
    MSC_CODE,
    CATEGORY
}